name = "tivaco boroda" # Замените на уникальное имя вашего проекта
compatibility_date = "2025-12-04" # Используйте текущую или более позднюю дату

[site]
bucket = "./out" # Это указывает Wrangler, что папка с вашим билдом называется out